"""
Models package for the Travel Agent API.
"""

from .base import (
    ResponseStatus,
    BaseResponse,
    ErrorResponse,
    HealthResponse,
    PaginationParams,
    PaginatedResponse,
    ValidationError,
    ValidationErrorResponse,
    APIConfig,
    DatabaseConfig,
    ExternalAPIConfig,
    LoggingConfig,
    validate_airport_code,
    validate_airline_code,
    validate_date_string,
)

from .flight import (
    TripType,
    SortBy,
    Stops,
    TravelClass,
    FlightSearchRequest,
    Airport,
    Flight,
    Layover,
    CarbonEmissions,
    FlightOption,
    PriceInsights,
    FlightSearchResponse,
    FlightSearchParams,
    ChatMessage,
    ChatRequest,
    ChatResponse,
)

from .hotel import (
    HotelSortBy,
    HotelRating,
    HotelClass,
    PropertyType,
    HotelSearchRequest,
    GPSCoordinates,
    Transportation,
    NearbyPlace,
    HotelImage,
    RateInfo,
    PriceSource,
    RatingBreakdown,
    StarRating,
    HotelProperty,
    HotelAd,
    HotelBrand,
    HotelSearchResponse,
    HotelSearchParams,
    TravelSearchParams,
    TravelChatResponse,
)

from .hotel import (
    HotelSortBy,
    HotelRating,
    HotelClass,
    PropertyType,
    HotelSearchRequest,
    HotelSearchResponse,
    HotelProperty,
    HotelAd,
    TravelSearchParams,
    HotelSearchParams,
)

from .hotel import (
    HotelSortBy,
    HotelRating,
    HotelClass,
    PropertyType,
    HotelSearchRequest,
    GPSCoordinates,
    Transportation,
    NearbyPlace,
    HotelImage,
    RateInfo,
    PriceSource,
    RatingBreakdown,
    StarRating,
    HotelProperty,
    HotelAd,
    HotelBrand,
    HotelSearchResponse,
    HotelSearchParams,
    TravelSearchParams,
    TravelChatResponse,
)

from .agent import (
    AgentState,
    AgentConfig,
    ToolCallResult,
    AgentMetrics,
    ConversationContext,
)

__all__ = [
    # Base models
    "ResponseStatus",
    "BaseResponse",
    "ErrorResponse",
    "HealthResponse",
    "PaginationParams",
    "PaginatedResponse",
    "ValidationError",
    "ValidationErrorResponse",
    "APIConfig",
    "DatabaseConfig",
    "ExternalAPIConfig",
    "LoggingConfig",
    "validate_airport_code",
    "validate_airline_code",
    "validate_date_string",
    
    # Flight models
    "TripType",
    "SortBy",
    "Stops",
    "TravelClass",
    "FlightSearchRequest",
    "Airport",
    "Flight",
    "Layover",
    "CarbonEmissions",
    "FlightOption",
    "PriceInsights",
    "FlightSearchResponse",
    "FlightSearchParams",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    
    # Hotel models
    "HotelSortBy",
    "HotelRating",
    "HotelClass",
    "PropertyType",
    "HotelSearchRequest",
    "GPSCoordinates",
    "Transportation",
    "NearbyPlace",
    "HotelImage",
    "RateInfo",
    "PriceSource",
    "RatingBreakdown",
    "StarRating",
    "HotelProperty",
    "HotelAd",
    "HotelBrand",
    "HotelSearchResponse",
    "HotelSearchParams",
    "TravelSearchParams",
    "TravelChatResponse",

    # Hotel models
    "HotelSortBy",
    "HotelRating",
    "HotelClass",
    "PropertyType",
    "HotelSearchRequest",
    "HotelSearchResponse",
    "HotelProperty",
    "HotelAd",
    "TravelSearchParams",
    "HotelSearchParams",

    # Hotel models
    "HotelSortBy",
    "HotelRating",
    "HotelClass",
    "PropertyType",
    "HotelSearchRequest",
    "GPSCoordinates",
    "Transportation",
    "NearbyPlace",
    "HotelImage",
    "RateInfo",
    "PriceSource",
    "RatingBreakdown",
    "StarRating",
    "HotelProperty",
    "HotelAd",
    "HotelBrand",
    "HotelSearchResponse",
    "HotelSearchParams",
    "TravelSearchParams",
    "TravelChatResponse",

    # Agent models
    "AgentState",
    "AgentConfig",
    "ToolCallResult",
    "AgentMetrics",
    "ConversationContext",
]
